name: Todolist Deployment Pipeline

on:
    push:
        branches: ["main","master"]
    pull_request:
        branches: ["main","master"]

env: 
    IMAGE_NAME: todolist_app

jobs:
    build:
        runs-on: ubuntu-latest
        
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Run Trivy FS
              uses: aquasecurity/trivy-action@master
              with:
                scan-type: "fs"
                scan-ref: "."
                format: "table"
                severity: "CRITICAL,HIGH"
                exit-code: 1
                ignore-unfixed: true
            
            - name: Build Docker Image
              run: |
                 docker build -f docker/Dockerfile -t ${{secrets.DOCKER_USERNAME}}/${{env.IMAGE_NAME}}:${{github.sha}} .

            - name: Run Trivy for scan image
              uses: aquasecurity/trivy-action@master
              with:
                image-ref : ${{secrets.DOCKER_USERNAME}}/${{env.IMAGE_NAME}}:${{github.sha}}
                format: "table"
                severity: "CRITICAL,HIGH"
                exit-code: 1
                ignore-unfixed: true
                vuln-type: "os,library"

            - name: Report Status
              if: always()
              run: echo "Security Scan Completed"

            - name: Login to Docker Hub
              uses: docker/login-action@v2
              with:
                username: ${{secrets.DOCKER_USERNAME}}
                password: ${{secrets.DOCKER_PASSWORD}}
            
            - name: Push Docker Image
              run: |
                 docker push ${{secrets.DOCKER_USERNAME}}/${{env.IMAGE_NAME}}:${{github.sha}}
            
            - name: Tag and Push latest
              run: |
                 docker tag ${{secrets.DOCKER_USERNAME}}/${{env.IMAGE_NAME}}.${{github.sha}} ${{secrets.DOCKER_USERNAME}}/${{env.IMAGE_NAME}}:latest
                 docker push ${{secrets.DOCKER_USERNAME}}/${{env.IMAGE_NAME}}:latest
    